Enhancement: Added verify.yml to molecule scenarios
NETWAYS/ansible-role-patroni pull request #13
Opened 2023-03-07 07:01 UTC by DanOPT

- Fixed minor connectivity bug
- Added verification tasks to molecule scenarios

2023-03-17 14:35 UTC, Saeid-Abadi submitted a review, later dismissed

2025-08-08 13:35 UTC, tbauriedel requested changes
Tasks are without fqcn. Would be nice to have it, but thats not mandatory inside the molecule checks I guess.

2025-08-08 13:35 UTC, tbauriedel commented on molecule/patroni-etcdv2-ssl/verify.yml
> +    - name:
Could you add a name here? Hard to identify in the job.

2025-08-08 13:35 UTC, tbauriedel commented on molecule/patroni-etcdv2-ssl/verify.yml
> +    - name:
Could you add a name here? Hard to identify in the job.

2025-08-08 13:35 UTC, tbauriedel commented on molecule/patroni-etcdv2-ssl/verify.yml
> +        msg: "{{ journalctl.stdout_lines }}"
```suggestion
# Remove comments to add journal logs for debugging
#    - name: Get journalctl -xe
#      shell: >
#        journalctl -xe
#        | tail -n100
#      register: journalctl

#    - name:
#      debug:
#        msg: "{{ journalctl.stdout_lines }}"
```

2025-08-08 13:35 UTC, tbauriedel commented on molecule/patroni-etcdv2-ssl/verify.yml
> +        msg: "{{ journalctl.stdout_lines }}"
```suggestion
# Remove comments to add journal logs for debugging
#    - name: Get journalctl -xe
#      shell: >
#        journalctl -xe
#        | tail -n100
#      register: journalctl

#    - name:
#      debug:
#        msg: "{{ journalctl.stdout_lines }}"
```

2025-08-08 13:35 UTC, tbauriedel commented on molecule/patroni-etcdv3-ssl/verify.yml
> +    - name:
Could you add a name here? Hard to identify in the job.

2025-08-08 13:35 UTC, tbauriedel commented on molecule/patroni-etcdv3-ssl/verify.yml
> +    - name:
Could you add a name here? Hard to identify in the job.

2025-08-08 13:35 UTC, tbauriedel commented on molecule/patroni-etcdv3-ssl/verify.yml
> +    - name:
Could you add a name here? Hard to identify in the job.

2025-08-08 13:35 UTC, tbauriedel commented on molecule/patroni-etcdv3-ssl/verify.yml
> +        msg: "{{ journalctl.stdout_lines }}"
```suggestion
# Remove comments to add journal logs for debugging
#    - name: Get journalctl -xe
#      shell: >
#        journalctl -xe
#        | tail -n100
#      register: journalctl

#    - name:
#      debug:
#        msg: "{{ journalctl.stdout_lines }}"
```

2025-08-08 13:35 UTC, tbauriedel commented on molecule/patroni-etcdv3-ssl/verify.yml
> +        msg: "{{ journalctl.stdout_lines }}"
```suggestion
# Remove comments to add journal logs for debugging
#    - name: Get journalctl -xe
#      shell: >
#        journalctl -xe
#        | tail -n100
#      register: journalctl

#    - name:
#      debug:
#        msg: "{{ journalctl.stdout_lines }}"
```

2025-08-12 10:21 UTC, tbauriedel approved these changes

2025-08-12 10:53 UTC, merged